import type { NodeDef } from "./types"

export const inputNodes: NodeDef[] = [
  {
    type: "video",
    label: "Video",
    category: "input",
    description: "The clip this effect is applied to.",
    kinds: ["effect"],
    cheap: true,
    inputs: [],
    outputs: [{ id: "image", label: "Image", type: "color" }],
    emit: (c) => ({ image: `return ${c.source(0, "uv")};` }),
  },
  {
    type: "from",
    label: "From clip",
    category: "input",
    description: "The outgoing clip.",
    kinds: ["transition"],
    cheap: true,
    inputs: [],
    outputs: [{ id: "image", label: "Image", type: "color" }],
    emit: (c) => ({ image: `return ${c.source(0, "uv")};` }),
  },
  {
    type: "to",
    label: "To clip",
    category: "input",
    description: "The incoming clip.",
    kinds: ["transition"],
    cheap: true,
    inputs: [],
    outputs: [{ id: "image", label: "Image", type: "color" }],
    emit: (c) => ({ image: `return ${c.source(1, "uv")};` }),
  },
  {
    type: "progress",
    label: "Progress",
    category: "input",
    description: "How far through the transition we are: 0 at the start, 1 at the end.",
    kinds: ["transition"],
    cheap: true,
    inputs: [],
    outputs: [{ id: "value", label: "Progress", type: "float" }],
    emit: (c) => ({ value: `return ${c.progress()};` }),
  },
  {
    type: "time",
    label: "Time",
    category: "input",
    description: "Seconds since the start of the clip.",
    kinds: ["effect"],
    cheap: true,
    inputs: [{ id: "speed", label: "Speed", type: "float", default: 1, min: 0, max: 10 }],
    outputs: [{ id: "value", label: "Seconds", type: "float" }],
    emit: (c) => ({ value: `return ${c.time()} * ${c.in("speed")};` }),
  },
  {
    type: "uv",
    label: "Position",
    category: "input",
    description: "Where on screen the current pixel is. 0,0 is the top-left corner, 1,1 the bottom-right.",
    cheap: true,
    inputs: [],
    outputs: [
      { id: "uv", label: "Position", type: "vec2" },
      { id: "x", label: "X", type: "float" },
      { id: "y", label: "Y", type: "float" },
      { id: "dist", label: "Distance from centre", type: "float" },
    ],
    emit: (c) => {
      const r = c.res()
      return {
        uv: "return uv;",
        x: "return uv.x;",
        y: "return uv.y;",
        dist: `vec2 d = (uv - 0.5) * vec2(${r}.x / max(${r}.y, 1.0), 1.0);\n    return length(d) * 2.0;`,
      }
    },
  },
  {
    type: "resolution",
    label: "Frame size",
    category: "input",
    description: "Size of the frame in pixels, and its aspect ratio.",
    cheap: true,
    inputs: [],
    outputs: [
      { id: "size", label: "Size (px)", type: "vec2" },
      { id: "aspect", label: "Aspect", type: "float" },
    ],
    emit: (c) => ({
      size: `return ${c.res()};`,
      aspect: `return ${c.res()}.x / max(${c.res()}.y, 1.0);`,
    }),
  },
  {
    type: "number",
    label: "Number",
    category: "input",
    description: "A single value. Expose it as a slider to reuse one control across many nodes.",
    cheap: true,
    inputs: [{ id: "value", label: "Value", type: "float", default: 0.5, min: 0, max: 1 }],
    outputs: [{ id: "value", label: "Value", type: "float" }],
    emit: (c) => ({ value: `return ${c.in("value")};` }),
  },
  {
    type: "switch_value",
    label: "Switch",
    category: "input",
    description: "An on/off value (1 or 0). Expose it to give users a toggle.",
    cheap: true,
    inputs: [{ id: "on", label: "On", type: "float", default: 1, min: 0, max: 1, widget: "toggle" }],
    outputs: [{ id: "value", label: "Value", type: "float" }],
    emit: (c) => ({ value: `return ${c.in("on")} > 0.5 ? 1.0 : 0.0;` }),
  },
  {
    type: "color_value",
    label: "Color",
    category: "input",
    description: "A solid colour.",
    cheap: true,
    inputs: [{ id: "color", label: "Color", type: "color", default: [1, 0.76, 0.03, 1], widget: "swatch" }],
    outputs: [{ id: "color", label: "Color", type: "color" }],
    emit: (c) => ({ color: `return ${c.in("color")};` }),
  },
  {
    type: "point_value",
    label: "Point",
    category: "input",
    description: "A position on screen.",
    cheap: true,
    inputs: [{ id: "point", label: "Point", type: "vec2", default: [0.5, 0.5], min: 0, max: 1, widget: "point" }],
    outputs: [{ id: "point", label: "Point", type: "vec2" }],
    emit: (c) => ({ point: `return ${c.in("point")};` }),
  },
  {
    type: "image",
    label: "Image",
    category: "input",
    description: "A picture you upload: an overlay, a texture, a logo.",
    cheap: true,
    inputs: [
      { id: "scale", label: "Repeat", type: "float", default: 1, min: 0.1, max: 20 },
    ],
    options: [{ id: "asset", label: "Picture", kind: "asset" }],
    outputs: [
      { id: "image", label: "Image", type: "color" },
      { id: "alpha", label: "Alpha", type: "float" },
    ],
    emit: (c) => ({
      image: `return ${c.asset(`uv * ${c.in("scale")}`)};`,
      alpha: `return ${c.asset(`uv * ${c.in("scale")}`)}.a;`,
    }),
  },
]
