import { color, effect, float, type Starter } from "../builder"

export const mathEffects: Starter[] = [
  effect("Complex power", "artistic", "The frame raised to a power as a complex number: a conformal fold that keeps every angle.", (g) => {
    const v = g.add("video", 0, 0)
    const z = g.add("complex_math", 1, 1, { n: g.param(float("power", "Power", 2, -4, 6)), zoom: g.param(float("zoom", "Zoom", 2, 0.5, 6)) }, { op: "pow" })
    const s = g.add("sample_at", 2, 0, {}, { edge: "mirror" })
    const o = g.output(3)
    g.link(v, "image", s, "image")
    g.link(z, "p", s, "p")
    g.link(s, "image", o, "image")
  }),

  effect("Möbius drift", "artistic", "A Möbius transform whose pole wanders, bending the frame into slowly flowing circles.", (g) => {
    const v = g.add("video", 0, 0)
    const amount = g.param(float("wander", "Wander", 0.5, 0, 0.9))
    const rate = g.param(float("drift", "Drift speed", 0.15, 0, 1))
    const lx = g.add("lfo", 0, 1, { rate, min: -1, max: 1 })
    const ly = g.add("lfo", 0, 2, { rate, min: -1, max: 1, phase: 0.25 })
    const w = g.add("combine_point", 1, 1)
    const ws = g.add("vector_math", 2, 1, { s: amount }, { op: "scale" })
    const z = g.add("complex_math", 3, 1, { zoom: g.param(float("zoom", "Zoom", 2, 0.5, 6)) }, { op: "mobius" })
    const s = g.add("sample_at", 4, 0, {}, { edge: "mirror" })
    const o = g.output(5)
    g.link(lx, "value", w, "x")
    g.link(ly, "value", w, "y")
    g.link(w, "p", ws, "a")
    g.link(ws, "p", z, "w")
    g.link(v, "image", s, "image")
    g.link(z, "p", s, "p")
    g.link(s, "image", o, "image")
  }),

  effect("Relief light", "artistic", "Brightness read as height and lit from the side, so the picture looks embossed in metal or clay.", (g) => {
    const v = g.add("video", 0, 0)
    const l = g.add("split_color", 1, 1)
    const d = g.add("derivative", 2, 1, { spacing: 1.5 })
    const light = g.add("vector_math", 2, 2, { a: [1, 0], s: g.param(float("lightAngle", "Light angle", 135, -180, 180)) }, { op: "rotate" })
    const dot = g.add("vector_measure", 3, 1)
    const k = g.add("math", 4, 1, { b: g.param(float("depth", "Depth", 0.004, 0, 0.02)) }, { op: "mul" })
    const h = g.add("math", 5, 1, { b: 0.5 }, { op: "add" })
    const bl = g.add("blend", 6, 0, { opacity: g.param(float("relief", "Strength", 0.9, 0, 1)) }, { mode: "overlay" })
    const o = g.output(7)
    g.link(v, "image", l, "color")
    g.link(l, "l", d, "x")
    g.link(d, "grad", dot, "a")
    g.link(light, "p", dot, "b")
    g.link(dot, "dot", k, "a")
    g.link(k, "value", h, "a")
    g.link(v, "image", bl, "base")
    g.link(h, "value", bl, "layer")
    g.link(bl, "image", o, "image")
  }),

  effect("Topographic", "artistic", "Contour lines traced through the brightness like a hiking map, the same width on steep and gentle slopes.", (g) => {
    const v = g.add("video", 0, 0)
    const blur = g.add("blur", 1, 1, { radius: 3 })
    const l = g.add("split_color", 2, 1)
    const n = g.add("math", 3, 1, { b: g.param(float("contours", "Lines", 12, 2, 40)) }, { op: "mul" })
    const fr = g.add("func", 4, 1, {}, { fn: "fract" })
    const c = g.add("math", 5, 1, { b: 0.5 }, { op: "sub" })
    const ab = g.add("func", 6, 1, {}, { fn: "abs" })
    const dist = g.add("math", 7, 1, { a: 0.5 }, { op: "sub" })
    const d = g.add("derivative", 4, 2)
    const res = g.add("resolution", 4, 3)
    const hgt = g.add("split_point", 5, 3)
    const perPx = g.add("math", 6, 2, {}, { op: "div" })
    const px = g.add("math", 8, 1, {}, { op: "div" })
    const mask = g.add("remap", 9, 1, { inMin: 0.4, inMax: g.param(float("lineWidth", "Line width (px)", 1.4, 0.6, 4)), outMin: 1, outMax: 0 })
    const ink = g.add("color_value", 9, 2, { color: g.param(color("lineColor", "Line colour", "#fff3d6")) })
    const mix = g.add("mix", 10, 0)
    const o = g.output(11)
    g.link(v, "image", blur, "image")
    g.link(blur, "image", l, "color")
    g.link(l, "l", n, "a")
    g.link(n, "value", fr, "x")
    g.link(fr, "value", c, "a")
    g.link(c, "value", ab, "x")
    g.link(ab, "value", dist, "b")
    g.link(n, "value", d, "x")
    g.link(res, "size", hgt, "p")
    g.link(d, "slope", perPx, "a")
    g.link(hgt, "y", perPx, "b")
    g.link(dist, "value", px, "a")
    g.link(perPx, "value", px, "b")
    g.link(px, "value", mask, "x")
    g.link(v, "image", mix, "a")
    g.link(ink, "color", mix, "b")
    g.link(mask, "value", mix, "amount")
    g.link(mix, "image", o, "image")
  }),

  effect("Curl flow", "dreamy", "The picture drifts along swirling currents that never bunch up or thin out.", (g) => {
    const v = g.add("video", 0, 0)
    const n = g.add("noise", 0, 1, { scale: g.param(float("swirlSize", "Swirl size", 3, 1, 10)), speed: g.param(float("flowSpeed", "Flow speed", 0.15, 0, 1)) }, { style: "smooth" })
    const d = g.add("derivative", 1, 1, { spacing: 2 })
    const perp = g.add("vector_math", 2, 1, {}, { op: "perp" })
    const k = g.add("vector_math", 3, 1, { s: g.param(float("flow", "Strength", 0.01, 0, 0.05)) }, { op: "scale" })
    const pos = g.add("uv", 3, 2)
    const p = g.add("vector_math", 4, 1, {}, { op: "add" })
    const s = g.add("sample_at", 5, 0, {}, { edge: "mirror" })
    const o = g.output(6)
    g.link(n, "value", d, "x")
    g.link(d, "grad", perp, "a")
    g.link(perp, "p", k, "a")
    g.link(pos, "uv", p, "a")
    g.link(k, "p", p, "b")
    g.link(v, "image", s, "image")
    g.link(p, "p", s, "p")
    g.link(s, "image", o, "image")
  }),

  effect("Pool caustics", "dreamy", "Rippling bright lines like sunlight through a swimming pool, focused where the water's surface bends light together.", (g) => {
    const v = g.add("video", 0, 0)
    const n = g.add("noise", 0, 1, { scale: g.param(float("waveSize", "Wave size", 5, 2, 12)), speed: g.param(float("waveSpeed", "Wave speed", 0.3, 0, 1.5)) }, { style: "smooth" })
    const d = g.add("derivative", 1, 1, { spacing: 2 })
    const k = g.add("vector_math", 2, 1, { s: g.param(float("refraction", "Refraction", 0.012, 0, 0.04)) }, { op: "scale" })
    const pos = g.add("uv", 2, 2)
    const p = g.add("vector_math", 3, 1, {}, { op: "add" })
    const j = g.add("jacobian", 4, 2, { spacing: 2 })
    const focus = g.add("math", 5, 2, { a: 1 }, { op: "div" })
    const ab = g.add("func", 6, 2, {}, { fn: "abs" })
    const bright = g.add("remap", 7, 2, { inMin: 1, inMax: 3, outMin: 0, outMax: 1 })
    const lit = g.add("tint", 8, 2, { color: g.param(color("lightColor", "Light colour", "#d8fbff")), amount: 1 })
    const s = g.add("sample_at", 4, 0)
    const bl = g.add("blend", 9, 0, { opacity: g.param(float("caustics", "Caustics", 0.6, 0, 1)) }, { mode: "screen" })
    const o = g.output(10)
    g.link(n, "value", d, "x")
    g.link(d, "grad", k, "a")
    g.link(pos, "uv", p, "a")
    g.link(k, "p", p, "b")
    g.link(p, "p", j, "p")
    g.link(j, "det", focus, "b")
    g.link(focus, "value", ab, "x")
    g.link(ab, "value", bright, "x")
    g.link(bright, "value", lit, "image")
    g.link(v, "image", s, "image")
    g.link(p, "p", s, "p")
    g.link(s, "image", bl, "base")
    g.link(lit, "image", bl, "layer")
    g.link(bl, "image", o, "image")
  }),

  effect("Funhouse shear", "funny", "The picture leans and stretches back and forth like a funhouse mirror.", (g) => {
    const v = g.add("video", 0, 0)
    const lean = g.param(float("lean", "Lean", 0.35, 0, 1))
    const rate = g.param(float("wobbleRate", "Speed", 0.5, 0, 3))
    const wave = g.add("lfo", 0, 1, { rate, min: -1, max: 1 })
    const b = g.add("math", 1, 1, { b: lean }, { op: "mul" })
    const m = g.add("math", 2, 1, { b: -0.5 }, { op: "mul" })
    const sq = g.add("lfo", 0, 2, { rate, min: 0.85, max: 1.15, phase: 0.25 })
    const w = g.add("matrix_warp", 3, 0, {}, { transparent: false })
    const o = g.output(4)
    g.link(wave, "value", b, "a")
    g.link(b, "value", m, "a")
    g.link(b, "value", w, "m01")
    g.link(m, "value", w, "m10")
    g.link(sq, "value", w, "m11")
    g.link(v, "image", w, "image")
    g.link(w, "image", o, "image")
  }),
]
