import { color, effect, float, personMatte, type Starter } from "../builder"

export const personEffects: Starter[] = [
  effect("Clone parade", "impact", "Two glowing copies of the person step out to either side, scaled from their feet with a linear transform.", (g) => {
    const v = g.add("video", 0, 0)
    const mask = personMatte(g, 0, 4, "stage-model")
    const sway = g.add("lfo", 0, 1, { rate: g.param(float("swayRate", "Sway speed", 0.5, 0, 3)), min: 0.8, max: 1 })
    const off = g.add("math", 1, 1, { a: g.param(float("spread", "Spread", 0.28, 0, 0.5)) }, { op: "mul" })
    const right = g.add("combine_point", 2, 1, { y: 0 })
    const left = g.add("vector_math", 3, 1, { s: -1 }, { op: "scale" })
    const size = g.param(float("cloneSize", "Clone size", 0.9, 0.5, 1.2))
    // Scaled about the feet so the clones stand on the same floor.
    const lt = (row: number) =>
      g.add("linear_transform", 4, row, { m00: size, m11: size, origin: [0.5, 1] }, { inverse: true })
    const pr = lt(2)
    const pl = lt(3)
    const imgR = g.add("sample_at", 5, 0, {}, { edge: "transparent" })
    const imgL = g.add("sample_at", 5, 1, {}, { edge: "transparent" })
    const mR = g.add("sample_at", 5, 2, {}, { edge: "transparent" })
    const mL = g.add("sample_at", 5, 3, {}, { edge: "transparent" })
    const tintAmt = g.param(float("cloneTint", "Clone tint", 0.45, 0, 1))
    const tR = g.add("tint", 6, 0, { color: g.param(color("rightColor", "Right clone", "#ff3d7f")), amount: tintAmt })
    const tL = g.add("tint", 6, 1, { color: g.param(color("leftColor", "Left clone", "#3dd2ff")), amount: tintAmt })
    const aR = g.add("split_color", 6, 2)
    const aL = g.add("split_color", 6, 3)
    const both = g.add("blend", 7, 3, {}, { mode: "add" })
    const halo = g.add("blur", 8, 3, { radius: g.param(float("haloSize", "Halo size", 18, 2, 48)) })
    const haloA = g.add("split_color", 9, 3)
    const haloCol = g.add("mix", 10, 3, { b: g.param(color("haloColor", "Halo", "#ff4f6d")) })
    const lit = g.add("blend", 8, 0, { opacity: g.param(float("halo", "Halo glow", 0.9, 0, 1)) }, { mode: "screen" })
    const withR = g.add("mix", 9, 0)
    const withL = g.add("mix", 10, 0)
    const front = g.add("mix", 11, 0)
    const o = g.output(12)
    g.link(sway, "value", off, "b")
    g.link(off, "value", right, "x")
    g.link(right, "p", left, "a")
    g.link(left, "p", pr, "offset")
    g.link(right, "p", pl, "offset")
    for (const [p, img, m] of [[pr, imgR, mR], [pl, imgL, mL]]) {
      g.link(p, "p", img, "p")
      g.link(p, "p", m, "p")
      g.link(v, "image", img, "image")
      g.link(mask, "mask", m, "image")
    }
    g.link(imgR, "image", tR, "image")
    g.link(imgL, "image", tL, "image")
    g.link(mR, "image", aR, "color")
    g.link(mL, "image", aL, "color")
    g.link(mR, "image", both, "base")
    g.link(mL, "image", both, "layer")
    g.link(both, "image", halo, "image")
    g.link(halo, "image", haloA, "color")
    g.link(haloA, "r", haloCol, "amount")
    g.link(v, "image", lit, "base")
    g.link(haloCol, "image", lit, "layer")
    g.link(lit, "image", withR, "a")
    g.link(tR, "image", withR, "b")
    g.link(aR, "r", withR, "amount")
    g.link(withR, "image", withL, "a")
    g.link(tL, "image", withL, "b")
    g.link(aL, "r", withL, "amount")
    g.link(withL, "image", front, "a")
    g.link(v, "image", front, "b")
    g.link(mask, "mask", front, "amount")
    g.link(front, "image", o, "image")
  }),

  effect("Neon outline", "impact", "A glowing line traces the person. The matte's gradient finds the edge, and its direction sets the colour, so the hue wheels around the body.", (g) => {
    const v = g.add("video", 0, 0)
    const mask = personMatte(g, 0, 2)
    const d = g.add("derivative", 1, 2, { spacing: 2 })
    const res = g.add("resolution", 1, 3)
    const hgt = g.add("split_point", 2, 3)
    const perPx = g.add("math", 3, 2, {}, { op: "div" })
    const edge = g.add("smoothstep", 4, 2, { low: 0.02, high: g.param(float("lineSoftness", "Softness", 0.18, 0.05, 0.5)) })
    const ang = g.add("vector_measure", 2, 4)
    const clock = g.add("time", 2, 5)
    const spin = g.add("math", 3, 5, { b: g.param(float("colorSpin", "Colour speed (°/s)", 90, -360, 360)) }, { op: "mul" })
    const hue = g.add("math", 4, 4, {}, { op: "add" })
    const ink = g.add("color_value", 4, 3, { color: g.param(color("neonColor", "Neon colour", "#00e5ff")) })
    const shift = g.add("hue_shift", 5, 3)
    const line = g.add("mix", 6, 2)
    const glow = g.add("glow", 7, 2, { threshold: 0, radius: g.param(float("neonGlow", "Glow size", 14, 2, 48)), intensity: g.param(float("neonIntensity", "Glow", 1.8, 0, 4)) })
    const dark = g.add("brightness_contrast", 1, 0, { brightness: g.param(float("backdrop", "Background", -0.35, -1, 0)) })
    const base = g.add("mix", 2, 0)
    const pulse = g.add("lfo", 7, 1, { rate: g.param(float("pulseRate", "Pulse speed", 2, 0, 8)), min: 0.55, max: 1 })
    const out = g.add("blend", 8, 0, {}, { mode: "add" })
    const o = g.output(9)
    g.link(mask, "mask", d, "x")
    g.link(res, "size", hgt, "p")
    g.link(d, "slope", perPx, "a")
    g.link(hgt, "y", perPx, "b")
    g.link(perPx, "value", edge, "x")
    g.link(d, "grad", ang, "a")
    g.link(clock, "value", spin, "a")
    g.link(ang, "angle", hue, "a")
    g.link(spin, "value", hue, "b")
    g.link(ink, "color", shift, "image")
    g.link(hue, "value", shift, "degrees")
    g.link(shift, "image", line, "b")
    g.link(edge, "value", line, "amount")
    g.link(line, "image", glow, "image")
    g.link(v, "image", dark, "image")
    g.link(dark, "image", base, "a")
    g.link(v, "image", base, "b")
    g.link(mask, "mask", base, "amount")
    g.link(base, "image", out, "base")
    g.link(glow, "image", out, "layer")
    g.link(pulse, "value", out, "opacity")
    g.link(out, "image", o, "image")
  }),

  effect("Sticker pop", "artistic", "The person peels off as a tilted, wobbling sticker with a white border and drop shadow over a soft background.", (g) => {
    const v = g.add("video", 0, 0)
    const mask = personMatte(g, 0, 5, "stage-model")
    const wob = g.add("lfo", 0, 1, { rate: g.param(float("wobbleSpeed", "Wobble speed", 0.8, 0, 4)), min: -1, max: 1 })
    const swing = g.add("math", 1, 1, { b: g.param(float("wobble", "Wobble (°)", 3, 0, 15)) }, { op: "mul" })
    const angle = g.add("math", 2, 1, { b: g.param(float("tilt", "Tilt (°)", -6, -30, 30)) }, { op: "add" })
    const rad = g.add("math", 3, 1, { b: Math.PI / 180 }, { op: "mul" })
    const cos = g.add("func", 4, 1, {}, { fn: "cos" })
    const sin = g.add("func", 4, 2, {}, { fn: "sin" })
    const size = g.param(float("stickerSize", "Size", 1.08, 0.7, 1.4))
    const a = g.add("math", 5, 1, { b: size }, { op: "mul" })
    const c = g.add("math", 5, 2, { b: size }, { op: "mul" })
    const b = g.add("func", 6, 2, {}, { fn: "neg" })
    // Rotation × scale matrix [[s·cos, −s·sin], [s·sin, s·cos]], inverted so the sticker turns forward.
    const pt = g.add("linear_transform", 7, 1, { origin: [0.5, 0.6] }, { inverse: true })
    const person = g.add("sample_at", 8, 0, {}, { edge: "transparent" })
    const pm = g.add("sample_at", 8, 3, {}, { edge: "transparent" })
    const pa = g.add("split_color", 9, 3)
    const grow = g.add("blur", 9, 4, { radius: g.param(float("border", "Border (px)", 10, 2, 30)) })
    const growA = g.add("split_color", 10, 4)
    const border = g.add("smoothstep", 11, 4, { low: 0.03, high: 0.1 })
    const pos = g.add("uv", 9, 5)
    const shift = g.add("vector_math", 10, 5, { b: [-0.012, -0.022] }, { op: "add" })
    const sh = g.add("sample_at", 11, 5)
    const shA = g.add("split_color", 12, 5)
    const shM = g.add("smoothstep", 13, 5, { low: 0.02, high: 0.5 })
    const shK = g.add("math", 14, 5, { b: g.param(float("shadow", "Shadow", 0.55, 0, 1)) }, { op: "mul" })
    const soft = g.add("blur", 1, 0, { radius: g.param(float("bgBlur", "Background blur", 14, 0, 48)) })
    const dim = g.add("brightness_contrast", 2, 0, { brightness: -0.15 })
    const shadowed = g.add("mix", 12, 0, { b: [0, 0, 0, 1] })
    const bordered = g.add("mix", 13, 0, { b: g.param(color("borderColor", "Border colour", "#ffffff")) })
    const final = g.add("mix", 14, 0)
    const o = g.output(15)
    g.link(wob, "value", swing, "a")
    g.link(swing, "value", angle, "a")
    g.link(angle, "value", rad, "a")
    g.link(rad, "value", cos, "x")
    g.link(rad, "value", sin, "x")
    g.link(cos, "value", a, "a")
    g.link(sin, "value", c, "a")
    g.link(c, "value", b, "x")
    g.link(a, "value", pt, "m00")
    g.link(b, "value", pt, "m01")
    g.link(c, "value", pt, "m10")
    g.link(a, "value", pt, "m11")
    g.link(v, "image", person, "image")
    g.link(pt, "p", person, "p")
    g.link(mask, "mask", pm, "image")
    g.link(pt, "p", pm, "p")
    g.link(pm, "image", pa, "color")
    g.link(pm, "image", grow, "image")
    g.link(grow, "image", growA, "color")
    g.link(growA, "r", border, "x")
    g.link(pos, "uv", shift, "a")
    g.link(grow, "image", sh, "image")
    g.link(shift, "p", sh, "p")
    g.link(sh, "image", shA, "color")
    g.link(shA, "r", shM, "x")
    g.link(shM, "value", shK, "a")
    g.link(v, "image", soft, "image")
    g.link(soft, "image", dim, "image")
    g.link(dim, "image", shadowed, "a")
    g.link(shK, "value", shadowed, "amount")
    g.link(shadowed, "image", bordered, "a")
    g.link(border, "value", bordered, "amount")
    g.link(bordered, "image", final, "a")
    g.link(person, "image", final, "b")
    g.link(pa, "r", final, "amount")
    g.link(final, "image", o, "image")
  }),

  effect("Focus punch", "impact", "On every beat the background zooms, smears and splits into RGB while the person stays sharp.", (g) => {
    const v = g.add("video", 0, 0)
    const mask = personMatte(g, 0, 3)
    const beat = g.add("lfo", 0, 1, { rate: g.param(float("bps", "Beats per second", 2, 0.25, 8)), min: 0, max: 1 }, { shape: "saw" })
    const decay = g.add("func", 1, 1, {}, { fn: "oneminus" })
    const pulse = g.add("math", 2, 1, { b: 3 }, { op: "pow" })
    const blurK = g.add("math", 3, 1, { b: g.param(float("punch", "Punch", 0.3, 0, 1)) }, { op: "mul" })
    const zoomK = g.add("remap", 3, 2, { outMin: 1, outMax: 1.08 })
    const splitK = g.add("math", 3, 3, { b: g.param(float("split", "Colour split (px)", 14, 0, 40)) }, { op: "mul" })
    const zoom = g.add("zoom", 4, 0)
    const zb = g.add("zoom_blur", 5, 0)
    const rgb = g.add("chromatic", 6, 0)
    const front = g.add("mix", 7, 0)
    const o = g.output(8)
    g.link(beat, "value", decay, "x")
    g.link(decay, "value", pulse, "a")
    g.link(pulse, "value", blurK, "a")
    g.link(pulse, "value", zoomK, "x")
    g.link(pulse, "value", splitK, "a")
    g.link(v, "image", zoom, "image")
    g.link(zoomK, "value", zoom, "amount")
    g.link(zoom, "image", zb, "image")
    g.link(blurK, "value", zb, "strength")
    g.link(zb, "image", rgb, "image")
    g.link(splitK, "value", rgb, "amount")
    g.link(rgb, "image", front, "a")
    g.link(v, "image", front, "b")
    g.link(mask, "mask", front, "amount")
    g.link(front, "image", o, "image")
  }),

  effect("Vortex backdrop", "dreamy", "The background twists into a whirlpool around the person. The Jacobian's curl lights up where it spins hardest.", (g) => {
    const v = g.add("video", 0, 0)
    const mask = personMatte(g, 0, 5)
    const pos = g.add("uv", 0, 1)
    const d = g.add("vector_math", 1, 1, { b: [0.5, 0.5] }, { op: "sub" })
    const r = g.add("vector_measure", 2, 2)
    const rr = g.add("math", 3, 2, { b: g.param(float("vortexSize", "Size", 0.45, 0.1, 1.5)) }, { op: "div" })
    const sq = g.add("func", 4, 2, {}, { fn: "square" })
    const neg = g.add("func", 5, 2, {}, { fn: "neg" })
    const fall = g.add("func", 6, 2, {}, { fn: "exp" })
    const swirl = g.add("lfo", 5, 3, { rate: g.param(float("vortexSpeed", "Speed", 0.2, 0, 2)), min: -1, max: 1 })
    const amt = g.add("math", 6, 3, { b: g.param(float("twist", "Twist (°)", 240, 0, 720)) }, { op: "mul" })
    const ang = g.add("math", 7, 2, {}, { op: "mul" })
    const rot = g.add("vector_math", 8, 1, {}, { op: "rotate" })
    const p = g.add("vector_math", 9, 1, { b: [0.5, 0.5] }, { op: "add" })
    const bg = g.add("sample_at", 10, 0, {}, { edge: "mirror" })
    const j = g.add("jacobian", 10, 2, { spacing: 2 })
    const curl = g.add("func", 11, 2, {}, { fn: "abs" })
    const glowAmt = g.add("remap", 12, 2, { inMin: 0, inMax: 4 })
    const lightCol = g.add("mix", 13, 2, { b: g.param(color("swirlColor", "Swirl light", "#8a6bff")) })
    const lit = g.add("blend", 11, 0, { opacity: g.param(float("swirlGlow", "Swirl glow", 0.6, 0, 1)) }, { mode: "screen" })
    const front = g.add("mix", 12, 0)
    const o = g.output(14)
    g.link(pos, "uv", d, "a")
    g.link(d, "p", r, "a")
    g.link(r, "length", rr, "a")
    g.link(rr, "value", sq, "x")
    g.link(sq, "value", neg, "x")
    g.link(neg, "value", fall, "x")
    g.link(swirl, "value", amt, "a")
    g.link(fall, "value", ang, "a")
    g.link(amt, "value", ang, "b")
    g.link(d, "p", rot, "a")
    g.link(ang, "value", rot, "s")
    g.link(rot, "p", p, "a")
    g.link(v, "image", bg, "image")
    g.link(p, "p", bg, "p")
    g.link(p, "p", j, "p")
    g.link(j, "curl", curl, "x")
    g.link(curl, "value", glowAmt, "x")
    g.link(glowAmt, "value", lightCol, "amount")
    g.link(bg, "image", lit, "base")
    g.link(lightCol, "image", lit, "layer")
    g.link(lit, "image", front, "a")
    g.link(v, "image", front, "b")
    g.link(mask, "mask", front, "amount")
    g.link(front, "image", o, "image")
  }),

  effect("Aura rings", "dreamy", "Rings of light ripple outward from the person, bending the background along the gradient of a blurred matte.", (g) => {
    const v = g.add("video", 0, 0)
    const mask = personMatte(g, 0, 5)
    const spread = g.add("blur", 1, 3, { radius: g.param(float("auraSize", "Aura size", 40, 8, 64)) })
    const field = g.add("split_color", 2, 3)
    const n = g.add("math", 3, 3, { b: g.param(float("rings", "Rings", 8, 2, 24)) }, { op: "mul" })
    const clock = g.add("time", 3, 4, { speed: g.param(float("ringSpeed", "Speed", 1.2, 0, 5)) })
    const phase = g.add("math", 4, 3, {}, { op: "add" })
    const fr = g.add("func", 5, 3, {}, { fn: "fract" })
    const centred = g.add("math", 6, 3, { b: 0.5 }, { op: "sub" })
    const ab = g.add("func", 7, 3, {}, { fn: "abs" })
    const ring = g.add("smoothstep", 8, 3, { low: 0.36, high: 0.5 })
    const near = g.add("smoothstep", 4, 4, { low: 0.02, high: 0.3 })
    const outside = g.add("func", 4, 5, {}, { fn: "oneminus" })
    const fade = g.add("math", 5, 4, {}, { op: "mul" })
    const rm = g.add("math", 9, 3, {}, { op: "mul" })
    const d = g.add("derivative", 3, 2, { spacing: 2 })
    const k = g.add("math", 10, 2, { b: g.param(float("refraction", "Refraction", 0.0025, 0, 0.01)) }, { op: "mul" })
    const push = g.add("vector_math", 11, 1, {}, { op: "scale" })
    const pos = g.add("uv", 11, 2)
    const p = g.add("vector_math", 12, 1, {}, { op: "add" })
    const bg = g.add("sample_at", 13, 0)
    const light = g.add("mix", 12, 3, { b: g.param(color("auraColor", "Aura colour", "#ffb347")) })
    const lit = g.add("blend", 14, 0, { opacity: g.param(float("auraGlow", "Glow", 0.8, 0, 1)) }, { mode: "screen" })
    const front = g.add("mix", 15, 0)
    const o = g.output(16)
    g.link(mask, "mask", spread, "image")
    g.link(spread, "image", field, "color")
    g.link(field, "r", n, "a")
    g.link(n, "value", phase, "a")
    g.link(clock, "value", phase, "b")
    g.link(phase, "value", fr, "x")
    g.link(fr, "value", centred, "a")
    g.link(centred, "value", ab, "x")
    g.link(ab, "value", ring, "x")
    g.link(field, "r", near, "x")
    g.link(mask, "mask", outside, "x")
    g.link(near, "value", fade, "a")
    g.link(outside, "value", fade, "b")
    g.link(ring, "value", rm, "a")
    g.link(fade, "value", rm, "b")
    g.link(field, "r", d, "x")
    g.link(rm, "value", k, "a")
    g.link(d, "grad", push, "a")
    g.link(k, "value", push, "s")
    g.link(pos, "uv", p, "a")
    g.link(push, "p", p, "b")
    g.link(v, "image", bg, "image")
    g.link(p, "p", bg, "p")
    g.link(rm, "value", light, "amount")
    g.link(bg, "image", lit, "base")
    g.link(light, "image", lit, "layer")
    g.link(lit, "image", front, "a")
    g.link(v, "image", front, "b")
    g.link(mask, "mask", front, "amount")
    g.link(front, "image", o, "image")
  }),
]
