import { color, float, personMatte, type Starter, transition } from "../builder"

export const personTransitions: Starter[] = [
  transition("Silhouette portal", "geometric", "The person's outline becomes a window into the next clip and grows exponentially until it fills the frame, traced by a neon edge.", (g) => {
    const a = g.add("from", 0, 0)
    const b = g.add("to", 0, 1)
    const mask = personMatte(g, 0, 4)
    const p = g.add("progress", 0, 2)
    const sq = g.add("func", 1, 2, {}, { fn: "square" })
    const k = g.add("math", 2, 2, { b: g.param(float("growth", "Growth", 3.5, 1, 6)) }, { op: "mul" })
    const s = g.add("func", 3, 2, {}, { fn: "exp" })
    const at = g.param({ identifier: "portalCentre", displayName: "Grow from", type: "point", min: 0, max: 1, default: [0.5, 0.4] })
    // The silhouette scaled by s about a point on the person: sample the matte at the inverse.
    const lt = g.add("linear_transform", 4, 2, { origin: at }, { inverse: true })
    const pm = g.add("sample_at", 5, 3, {}, { edge: "transparent" })
    const inside = g.add("split_color", 6, 3)
    const d = g.add("derivative", 7, 3, { spacing: 2 })
    const res = g.add("resolution", 7, 4)
    const hgt = g.add("split_point", 8, 4)
    const perPx = g.add("math", 8, 3, {}, { op: "div" })
    const edge = g.add("smoothstep", 9, 3, { low: 0.02, high: 0.2 })
    const line = g.add("mix", 10, 3, { b: g.param(color("edgeColor", "Edge colour", "#4dfcff")) })
    const glow = g.add("glow", 11, 3, { threshold: 0, radius: 12, intensity: g.param(float("edgeGlow", "Edge glow", 1.6, 0, 4)) })
    const finish = g.add("smoothstep", 6, 1, { low: 0.85, high: 1 })
    const reveal = g.add("math", 7, 1, {}, { op: "max" })
    const mix = g.add("mix", 8, 0)
    const fadeEdge = g.add("func", 9, 1, {}, { fn: "oneminus" })
    const out = g.add("blend", 12, 0, {}, { mode: "add" })
    const o = g.output(13)
    g.link(p, "value", sq, "x")
    g.link(sq, "value", k, "a")
    g.link(k, "value", s, "x")
    g.link(s, "value", lt, "m00")
    g.link(s, "value", lt, "m11")
    g.link(mask, "mask", pm, "image")
    g.link(lt, "p", pm, "p")
    g.link(pm, "image", inside, "color")
    g.link(inside, "r", d, "x")
    g.link(res, "size", hgt, "p")
    g.link(d, "slope", perPx, "a")
    g.link(hgt, "y", perPx, "b")
    g.link(perPx, "value", edge, "x")
    g.link(edge, "value", line, "amount")
    g.link(line, "image", glow, "image")
    g.link(p, "value", finish, "x")
    g.link(inside, "r", reveal, "a")
    g.link(finish, "value", reveal, "b")
    g.link(a, "image", mix, "a")
    g.link(b, "image", mix, "b")
    g.link(reveal, "value", mix, "amount")
    g.link(finish, "value", fadeEdge, "x")
    g.link(mix, "image", out, "base")
    g.link(glow, "glow", out, "layer")
    g.link(fadeEdge, "value", out, "opacity")
    g.link(out, "image", o, "image")
  }),

  transition("Subject pop-through", "cinematic", "The person holds still in front while the world behind them punches through a zoom blur into the next clip, then they dissolve away.", (g) => {
    const a = g.add("from", 0, 0)
    const b = g.add("to", 0, 1)
    const mask = personMatte(g, 0, 4)
    const p = g.add("progress", 0, 2)
    const fade = g.add("ease", 1, 1, {}, { curve: "expo" })
    const peak = g.add("ease", 1, 2, {}, { curve: "peaksmooth" })
    const blurK = g.add("math", 2, 2, { b: g.param(float("punch", "Punch", 0.45, 0, 1)) }, { op: "mul" })
    const splitK = g.add("math", 2, 3, { b: g.param(float("split", "Colour split (px)", 18, 0, 40)) }, { op: "mul" })
    const bg = g.add("mix", 2, 0)
    const zb = g.add("zoom_blur", 3, 0)
    const rgb = g.add("chromatic", 4, 0)
    const leave = g.add("smoothstep", 2, 4, { low: g.param(float("holdUntil", "Person leaves at", 0.7, 0.3, 0.95)), high: 1 })
    const keep = g.add("func", 3, 4, {}, { fn: "oneminus" })
    const m = g.add("math", 4, 4, {}, { op: "mul" })
    const front = g.add("mix", 5, 0)
    const o = g.output(6)
    g.link(p, "value", fade, "t")
    g.link(p, "value", peak, "t")
    g.link(peak, "value", blurK, "a")
    g.link(peak, "value", splitK, "a")
    g.link(a, "image", bg, "a")
    g.link(b, "image", bg, "b")
    g.link(fade, "value", bg, "amount")
    g.link(bg, "image", zb, "image")
    g.link(blurK, "value", zb, "strength")
    g.link(zb, "image", rgb, "image")
    g.link(splitK, "value", rgb, "amount")
    g.link(p, "value", leave, "x")
    g.link(leave, "value", keep, "x")
    g.link(mask, "mask", m, "a")
    g.link(keep, "value", m, "b")
    g.link(rgb, "image", front, "a")
    g.link(a, "image", front, "b")
    g.link(m, "value", front, "amount")
    g.link(front, "image", o, "image")
  }),

  transition("Sticker fling", "stylized", "The person peels off as a white-bordered sticker and spins away off the top of the frame, uncovering the next clip.", (g) => {
    const a = g.add("from", 0, 0)
    const b = g.add("to", 0, 1)
    const mask = personMatte(g, 0, 6, "stage-model")
    const p = g.add("progress", 0, 2)
    const lift = g.add("ease", 1, 2, {}, { curve: "in" })
    const angle = g.add("math", 2, 2, { b: g.param(float("spin", "Spin (°)", 35, -180, 180)) }, { op: "mul" })
    const rad = g.add("math", 3, 2, { b: Math.PI / 180 }, { op: "mul" })
    const cos = g.add("func", 4, 2, {}, { fn: "cos" })
    const sin = g.add("func", 4, 3, {}, { fn: "sin" })
    const grow = g.add("remap", 2, 3, { outMin: 1, outMax: g.param(float("flingSize", "End size", 1.3, 0.5, 2)) })
    const m00 = g.add("math", 5, 2, {}, { op: "mul" })
    const m10 = g.add("math", 5, 3, {}, { op: "mul" })
    const m01 = g.add("func", 6, 3, {}, { fn: "neg" })
    const dx = g.add("math", 2, 4, { b: -0.25 }, { op: "mul" })
    const dy = g.add("math", 2, 5, { b: 1.4 }, { op: "mul" })
    const off = g.add("combine_point", 3, 4)
    // Rotate × scale, then move up; inverted so each pixel reads where the sticker came from.
    const pt = g.add("linear_transform", 7, 2, { origin: [0.5, 0.6] }, { inverse: true })
    const person = g.add("sample_at", 8, 0, {}, { edge: "transparent" })
    const pm = g.add("sample_at", 8, 4, {}, { edge: "transparent" })
    const pa = g.add("split_color", 9, 4)
    const thick = g.add("blur", 9, 5, { radius: g.param(float("border", "Border (px)", 10, 2, 30)) })
    const thickA = g.add("split_color", 10, 5)
    const border = g.add("smoothstep", 11, 5, { low: 0.03, high: 0.1 })
    const peel = g.add("smoothstep", 10, 6, { low: 0, high: 0.08 })
    const borderK = g.add("math", 12, 5, {}, { op: "mul" })
    const fade = g.add("smoothstep", 1, 1, { low: 0, high: 0.5 })
    const bg = g.add("mix", 2, 0)
    const bordered = g.add("mix", 10, 0, { b: g.param(color("borderColor", "Border colour", "#ffffff")) })
    const final = g.add("mix", 11, 0)
    const o = g.output(12)
    g.link(p, "value", lift, "t")
    g.link(lift, "value", angle, "a")
    g.link(angle, "value", rad, "a")
    g.link(rad, "value", cos, "x")
    g.link(rad, "value", sin, "x")
    g.link(lift, "value", grow, "x")
    g.link(cos, "value", m00, "a")
    g.link(grow, "value", m00, "b")
    g.link(sin, "value", m10, "a")
    g.link(grow, "value", m10, "b")
    g.link(m10, "value", m01, "x")
    g.link(m00, "value", pt, "m00")
    g.link(m01, "value", pt, "m01")
    g.link(m10, "value", pt, "m10")
    g.link(m00, "value", pt, "m11")
    g.link(lift, "value", dx, "a")
    g.link(lift, "value", dy, "a")
    g.link(dx, "value", off, "x")
    g.link(dy, "value", off, "y")
    g.link(off, "p", pt, "offset")
    g.link(a, "image", person, "image")
    g.link(pt, "p", person, "p")
    g.link(mask, "mask", pm, "image")
    g.link(pt, "p", pm, "p")
    g.link(pm, "image", pa, "color")
    g.link(pm, "image", thick, "image")
    g.link(thick, "image", thickA, "color")
    g.link(thickA, "r", border, "x")
    g.link(p, "value", peel, "x")
    g.link(border, "value", borderK, "a")
    g.link(peel, "value", borderK, "b")
    g.link(p, "value", fade, "x")
    g.link(a, "image", bg, "a")
    g.link(b, "image", bg, "b")
    g.link(fade, "value", bg, "amount")
    g.link(bg, "image", bordered, "a")
    g.link(borderK, "value", bordered, "amount")
    g.link(bordered, "image", final, "a")
    g.link(person, "image", final, "b")
    g.link(pa, "r", final, "amount")
    g.link(final, "image", o, "image")
  }),
]
